### ISSUE TITLE
Allow the EDS to be used with SLSC Switch

### ISSUE THREAD

**Issue by Alexbarp** [ni/niveristand-slsc-eds-custom-device#32]
The EDS is designed to change any property of the card. The SLSC Switch is designed to control the switches. If you have a card that has "properties" and "switches" to be control (like the SLSC-12251), then you probably would need to have both functionalities. I think we should "expand" the SLSC-EDS to allow the card to support the switches AND have some properties available to change.
(*This was reported by Burt Snover from SET).

**Comment by smithed180** [comment]
For this the SLSC reservation group comes into play. In order to support having the switch CD play nice with other SLSC CDs you need to have the reservation group match (an empty string apparently does not mean "don't reserve" but instead means "exclusive lock"). What we did for our projects was to use the module URL as the reservation group ie:
![image](https://user-images.githubusercontent.com/53264791/72285323-e0603700-3610-11ea-9b31-8252b6694cb8.png)
